x = input('Digite algo: ')
print('O tipo primitivo desta váriavel é {}'.format(type(x)))
print('O valor é apenas numérico: {}'.format(x.isnumeric()))
print('O valor é apenas alfabético: {}'.format(x.isalpha()))
print('O valor é número + alfabético: {}'.format(x.isalnum()))
print('O valor é um código ASCII: {}'.format(x.isascii()))
print('O valor é um dígito: {}'.format(x.isdigit()))
print('O valor é um número decimal: {}'.format(x.isdecimal()))
print('O valor é válido para um identificador: {}'.format(x.isidentifier()))
print('O valor é totalmente impresso na tela: {}'.format(x.isprintable()))
print('O valor é totalmente escrito em minúsculo: {}'.format(x.islower()))
print('O valor é totalmente escrito em maiúsculo: {}'.format(x.isupper()))
print('O valor possui algum tipo de quebra de linha: {}'.format(x.isspace()))
print('O valor possui todas as palavras iniciadas com letras maiúsculas: {}'.format(x.istitle()))